Repository JancoDVTDev/camPod, pull requests merged in 2020-03, with the labels that each got.

#7 updating file structure fir bitrise
  camPod/Classes/Models/Album.swift
  camPod/Classes/Models/User.swift
Labels: size/M

#8 Updated file structure
  camPod/Classes/ModelViews/AlbumViewModel.swift
  camPod/Classes/Models/User.swift
Labels: size/S

#9 Feature/create user model
  camPod.podspec
  camPod/Classes/CameraBehaviour/CameraBehaviourViewModel.swift
  camPod/Classes/ModelViews/CameraBehaviour.swift
  camPod/Classes/ModelViews/UserViewModel.swift
  camPod/Classes/Models/User.swift
  camPod/Classes/ReplaceMe.swift
  camPod/Classes/SignUpLogin/UserModel.swift
  camPod/Classes/SignUpLogin/UserSignUpLoginViewModel.swift
Labels: enhancement, size/L

#10 Development
  camPod.podspec
  camPod/Classes/CameraBehaviour/CameraBehaviourViewModel.swift
  camPod/Classes/ModelViews/CameraBehaviour.swift
  camPod/Classes/ModelViews/UserViewModel.swift
  camPod/Classes/Models/User.swift
  camPod/Classes/ReplaceMe.swift
  camPod/Classes/SignUpLogin/UserModel.swift
  camPod/Classes/SignUpLogin/UserSignUpLoginViewModel.swift
Labels: size/L

#11 Feature/album path structure and user integration
  camPod/Classes/Albums/ShowingAllUserAlbumsViewModel.swift
  camPod/Classes/CameraBehaviour/CameraBehaviourViewModel.swift
  camPod/Classes/Models/User.swift
  camPod/Classes/SignUpLogin/UserModel.swift
  camPod/Classes/SignUpLogin/UserSignUpLoginViewModel.swift
Labels: enhancement, size/L

#12 Update Files
  camPod/Classes/Albums/ShowingAllUserAlbumsViewModel.swift
  camPod/Classes/CameraBehaviour/CameraBehaviourViewModel.swift
  camPod/Classes/SignUpLogin/UserModel.swift
  camPod/Classes/SignUpLogin/UserSignUpLoginViewModel.swift
Labels: size/S

#13 Update all FIles to start work again
  camPod/Classes/Albums/ShowingAllUserAlbumsViewModel.swift
  camPod/Classes/SignUpLogin/UserModel.swift
  camPod/Classes/SignUpLogin/UserSignUpLoginViewModel.swift
Labels: size/M

#14 Forgot to change branch - Models and ViewModels restructured
  camPod/Classes/Albums/AlbumModel.swift
  camPod/Classes/Albums/ShowingAllUserAlbumsViewModel.swift
  camPod/Classes/ModelViews/UserViewModel.swift
  camPod/Classes/Models/User.swift
  camPod/Classes/SignUpLogin/UserModel.swift
  camPod/Classes/SignUpLogin/UserSignUpLoginViewModel.swift
Labels: size/L

#15 Album is now added and updated in collection view
  camPod/Classes/Albums/AlbumModel.swift
  camPod/Classes/Albums/AlbumViewModel.swift
  camPod/Classes/Albums/SingleAlbum.swift
  camPod/Classes/ModelViews/AlbumViewModel.swift
  camPod/Classes/SignUpLogin/User.swift
  camPod/Classes/SignUpLogin/UserModel.swift
  camPod/Classes/SignUpLogin/UserSignUpLoginViewModel.swift
Labels: enhancement, size/L

#16 Generate unique ID and Login, Signup and Password validation now in O…
  ObjectiveC/HelperFunctions/Helper.h
  ObjectiveC/HelperFunctions/Helper.m
  camPod/Classes/SignUpLogin/UserModel.swift
Labels: size/L

#19 Update Campod
  camPod/Classes/ObjectiveCHelperFunctions/ObjcHelper.m
Labels: size/S

#20 SwiftLint script added. Does not seem toe work though
  camPod/Classes/Albums/AlbumModel.swift
  camPod/Classes/Albums/SingleAlbum.swift
  camPod/Classes/ReplaceMe.swift
Labels: size/XS

#21 Swiftlint Added & Fully converted Objective C Feature
  camPod/Classes/Albums/AlbumModel.swift
  camPod/Classes/Albums/AlbumViewModel.swift
  camPod/Classes/Albums/SingleAlbum.swift
  camPod/Classes/CameraBehaviour/CameraBehaviourViewModel.swift
  camPod/Classes/SingleAlbumFeature/Model/SingleAlbumModelObjc.h
  camPod/Classes/SingleAlbumFeature/Model/SingleAlbumModelObjc.m
  camPod/Classes/SingleAlbumFeature/PhotoCell/PhotoCellCollectionViewCell.h
  camPod/Classes/SingleAlbumFeature/PhotoCell/PhotoCellCollectionViewCell.m
  camPod/Classes/SingleAlbumFeature/SingleAlbumObjCViewController.h
  camPod/Classes/SingleAlbumFeature/SingleAlbumObjCViewController.m
  camPod/Classes/SingleAlbumFeature/View/SingleAlbumObjCView.h
  camPod/Classes/SingleAlbumFeature/View/SingleAlbumObjCView.m
  camPod/Classes/SingleAlbumFeature/ViewModel/SingleAlbumObjCViewModel.h
  camPod/Classes/SingleAlbumFeature/ViewModel/SingleAlbumObjCViewModel.m
Labels: size/L

#23 Can take Picture and save to the album
  Example/Pods/Pods.xcodeproj/project.pbxproj
  Example/Pods/Pods.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Example/Pods/Pods.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Example/camPod.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Example/camPod/AppDelegate.swift
  camPod/Classes/Albums/AlbumModel.swift
  camPod/Classes/Albums/AlbumViewModel.swift
  camPod/Classes/Albums/ShowingAllUserAlbumsViewModel.swift
  camPod/Classes/Albums/SingleAlbum.swift
  camPod/Classes/CameraBehaviour/CameraBehaviourViewModel.swift
  camPod/Classes/ModelViews/CameraBehaviour.swift
  camPod/Classes/Models/Album.swift
  camPod/Classes/ObjectiveC/HelperFunctions/Helper.m
  camPod/Classes/ObjectiveCHelperFunctions/ObjcHelper.m
  camPod/Classes/ReplaceMe.swift
  camPod/Classes/SignUpLogin/User.swift
  camPod/Classes/SignUpLogin/UserModel.swift
  camPod/Classes/SignUpLogin/UserSignUpLoginViewModel.swift
  camPod/Classes/SingleAlbumFeature/Model/SingleAlbumModelObjc.h
  camPod/Classes/SingleAlbumFeature/Model/SingleAlbumModelObjc.m
  camPod/Classes/SingleAlbumFeature/View/SingleAlbumObjCView.h
  camPod/Classes/SingleAlbumFeature/View/SingleAlbumObjCView.m
  camPod/Classes/SingleAlbumFeature/View/SingleAlbumObjCViewController.h
  camPod/Classes/SingleAlbumFeature/View/SingleAlbumObjCViewController.m
  camPod/Classes/SingleAlbumFeature/ViewModel/SingleAlbumObjCViewModel.h
  camPod/Classes/SingleAlbumFeature/ViewModel/SingleAlbumObjCViewModel.m
Labels: enhancement, size/L

#24 Add a Codacy badge to README.md
  README.md
Labels: size/XS

#25 Feature/share album
  camPod/Classes/Albums/AlbumViewModel.swift
  camPod/Classes/QRCodeGenerator/View/QRCodeGeneratorObjCViewController.h
  camPod/Classes/QRCodeGenerator/View/QRCodeGeneratorObjCViewController.m
  camPod/Classes/QRCodeGenerator/ViewModel/QRCodeGeneratorObjCViewModel.h
  camPod/Classes/QRCodeGenerator/ViewModel/QRCodeGeneratorObjCViewModel.m
  camPod/Classes/SelectedImage/View/SelectedImageObjCViewController.h
  camPod/Classes/SelectedImage/View/SelectedImageObjCViewController.m
  camPod/Classes/SingleAlbumFeature/View/SingleAlbumObjCView.h
  camPod/Classes/SingleAlbumFeature/View/SingleAlbumObjCView.m
  camPod/Classes/SingleAlbumFeature/View/SingleAlbumObjCViewController.h
  camPod/Classes/SingleAlbumFeature/View/SingleAlbumObjCViewController.m
Labels: size/L

#26 Analytics implemented
  camPod/Classes/GoogleFirebaseAnalytics/NameConstants.swift
  camPod/Classes/GoogleFirebaseAnalytics/TrackFirebaseAnalytics.swift
  camPod/Classes/SingleAlbumFeature/View/SingleAlbumObjCViewController.h
  camPod/Classes/SingleAlbumFeature/View/SingleAlbumObjCViewController.m
Labels: size/M

#27 Delete Album Fully Functional
  camPod/Classes/Albums/AlbumViewModel.swift
  camPod/Classes/SingleAlbumFeature/View/SingleAlbumObjCViewController.h
  camPod/Classes/SingleAlbumFeature/View/SingleAlbumObjCViewController.m
  camPod/Classes/SingleAlbumFeature/ViewModel/SingleAlbumObjCViewModel.h
  camPod/Classes/SingleAlbumFeature/ViewModel/SingleAlbumObjCViewModel.m
Labels: size/L

#28 Updated Helper error Messages
  camPod/Classes/ObjectiveCHelperFunctions/ObjcHelper.m
Labels: size/XS
